### ISSUE TITLE
Get site running

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/nekovm.org#3]
I'm trying to build the server.hxml but I get this error

![image](https://cloud.githubusercontent.com/assets/576184/9016925/1f4e44b4-37d5-11e5-9925-c53f5ad7bd4a.png)

I already runned `haxe install server.hxml` which should install it's dependencies?

So I thought maybe I only need to do `ufront build` ?

![image](https://cloud.githubusercontent.com/assets/576184/9016988/62c1de68-37d5-11e5-8cd4-98285c457580.png)

.. or only `ufront server`?

![image](https://cloud.githubusercontent.com/assets/576184/9017077/bc36c7d8-37d5-11e5-89e0-3b4269cd5a94.png)
 
---
**update:** 
After some investigation I found that the import statements aren't correct (fixed here https://github.com/HaxeFoundation/nekovm.org/pull/4). I now added this on all source files:
```
import ufront.*;
import ufront.web.*;
import ufront.api.*;
```
But then I get this error:
![image](https://cloud.githubusercontent.com/assets/576184/9017467/0857c2ba-37d7-11e5-8634-8bb32329fa16.png)

This means there is something in detox incorrect.. Now I'm stuck..

How do I get the thing working :smile: ?

**Comment by jasononeil** [comment]
Sorry about this.  I built the site in a rush (the old one was causing performance issues) and forgot to switch to the release versions of libraries (I was using dev versions).

I'm cleaning it up now.

**Comment by jasononeil** [comment]
Okay, I've released the versions and put explicit version numbers in.  If you run `haxelib install all` now it should install correctly (and hopefully compile too!) 

I'll work on adding Travis support soon to keep an eye on it and make sure it's always ready to compile.

**Comment by jasononeil** [comment]
p.s. If there are still any issues, please re-open so I can address them.

**Comment by markknol** [comment]
I just tried to get it up and running, but it still fails. I did `haxelib install client.hxml` but still the imports are incorrect and after fixing those manually I get errors:

![image](https://cloud.githubusercontent.com/assets/576184/9245916/30f84c46-41a8-11e5-891f-42c68c18243f.png)

**Comment by jasononeil** [comment]
It looks like you've still got some git or dev versions in haxelib. If you run `haxelib list` to see which versions are in dev mode, and disable them, does it fix the problem?

**Comment by markknol** [comment]
![image](https://cloud.githubusercontent.com/assets/576184/9282758/f747460a-42ce-11e5-8ef0-ca2f15e3c70b.png)

I have no idea what version I need of which, can you help me out?

**Comment by markknol** [comment]
I did a clean install and resolved some dependencies (don't ask me which) and now it works.

**Comment by andyli** [comment]
I'm a bit confused. Do we still need to merge #4? Or should the site depend on git versions of ufront instead?
@jasononeil please clarify.
